### ISSUE TITLE
Missing file extension

### ISSUE THREAD

**Issue by alexander-albers** [SeineEloquenz/kit-ilias-opencast-downloader#5]
If the title of a video does not end with a file extension, the video gets downloaded and saved to a file without a file extension and cannot be opened right away. The extension should ideally check for any movie file extensions, and append `.mp4` if there is none. Related to https://github.com/SeineEloquenz/kit-ilias-opencast-downloader/commit/797b559f75c3fa52e50b7db471b4a07476e7a374.

I could submit a pull request if you want, but I'm not sure yet how I would check if a file extension is already included in the document title. Or can we just assume that all videos are mp4s and simply check if the name ends with .mp4?

Btw, thanks for the extension 👍

**Comment by SeineEloquenz** [comment]
Agreed, this is an oversight that should get fixed.
I don't really know how to check for the file extension if I'm honest.
I think it would be best to come up with a set of file extensions which are most common and check for those via regex or something like that.
Mp4 alone won't suffice, as I've already come across formats like m4a for example.
If you could open a PR that would be nice, as I'm quite limited on time atm.
Otherwise I would have to put this on hold for the time being.

PS: I'm glad people find the extension useful :+1:
